source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
# gem 'spring',        group: :development

gem 'thin'

gem 'uuidtools'
gem 'abongo', :git => 'git://github.com/teejteej/abongo.git'
gem 'metrics', :path => '../../'
gem 'mongo'
gem 'bson_ext'
gem 'redis'
